- name: Setup SSH and Deploy
  env:
    SERVER_HOST: ${{ secrets.SERVER_HOST }}
    SERVER_USER: ${{ secrets.SERVER_USER }}
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
  run: |
    mkdir -p ~/.ssh
    echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ls -lah ~/.ssh  # SSH 파일 확인 (디버깅용)
    cat ~/.ssh/id_rsa  # SSH 키 내용 확인 (디버깅 후 삭제)

    ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
      cd $DEPLOY_PATH
      git pull origin main
      npm install
      pm2 restart all
    EOF
